<a href="https://colab.research.google.com/github/jashwanth15/Machine-Learning/blob/main/Lab_1_numpy(1)_AP23110011398.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a=np.array([0,1,2])
print(a)

[0 1 2]


In [ ]:
print(type(a))

<class 'numpy.ndarray'>


In [ ]:
print(a.shape)

(3,)


In [ ]:
print(a[0])

0


In [ ]:
print(a[1])

1


In [ ]:
print(a[2])

2


In [ ]:
a[0]=5
print(a[0])

5


In [ ]:
b=np.array([[0,1,2],[4,5,6]])
print(b)

[[0 1 2]
 [4 5 6]]


In [ ]:
print(type(b))

<class 'numpy.ndarray'>


In [ ]:
print(b.shape)

(2, 3)


In [ ]:
print(b[0,0],b[0,1],b[1,0])

0 1 4


In [ ]:
a=np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
b=np.ones((3,3))
print(b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
c=np.full((3,3),7)
print(c)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [ ]:
d=np.full((2,2),9)
print(d)

[[9 9]
 [9 9]]


In [ ]:
d=np.random.random((3,3))
print(d)

[[0.38768035 0.45312799 0.35784138]
 [0.30267156 0.43909409 0.36454043]
 [0.60608239 0.31833613 0.2632799 ]]


In [ ]:
e=np.eye(3)
print(e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
f=np.array([2,3,1,0])
print(f)

[2 3 1 0]


In [ ]:
g=np.arange(10)
print(g)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
h=np.array([[0,1,2.0],[0,0,0],[1+1j,3.,2.]])
print(h)

[[0.+0.j 1.+0.j 2.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]
 [1.+1.j 3.+0.j 2.+0.j]]


In [ ]:
i=np.arange(1,8,dtype=float)
print(i)

[1. 2. 3. 4. 5. 6. 7.]


In [ ]:
j=np.linspace(2,4,5)
print(j)

[2.  2.5 3.  3.5 4. ]


In [ ]:
x=np.array([0,1])
y=np.array([2.0,3.0])
z=np.array([5,6])
print(x,y,z)

[0 1] [2. 3.] [5 6]


In [ ]:
print(x.dtype,y.dtype,z.dtype)

int64 float64 int64


In [ ]:
arr=np.array([[-1,2,0,4],[4,-0.5,6,0],[2.6,0,7,8],[3,-7,4,2.0]])
print(arr)

[[-1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]
 [ 2.6  0.   7.   8. ]
 [ 3.  -7.   4.   2. ]]


In [ ]:
temp=arr[:2,::2]
print(temp)

[[-1.  0.]
 [ 4.  6.]]


In [ ]:
temp=arr[[0,1,2,3],[3,2,1,0]]
print("(0,3),(1,2),(2,1),(3,0)\n",temp)

(0,3),(1,2),(2,1),(3,0)
 [4. 6. 0. 3.]


In [ ]:
cond=arr>0
temp=arr[cond]
print(temp)

[2.  4.  4.  6.  2.6 7.  8.  3.  4.  2. ]


In [ ]:
a=np.array([1,2,5,3])
print(a+1)

[2 3 6 4]


In [ ]:
print(a-3)

[-2 -1  2  0]


In [ ]:
print(a*10)

[10 20 50 30]


In [ ]:
print(a**2)

[ 1  4 25  9]


In [ ]:
a*=2
print(a)

[ 2  4 10  6]


In [ ]:
a=np.array([[1,2,3],[3,4,5],[9,6,0]])
print(a.T)#transpose

[[1 3 9]
 [2 4 6]
 [3 5 0]]


In [ ]:
arr=np.array([[1,5,6],[4,7,2],[3,1,9]])
print(arr.max())

9


In [ ]:
print(arr.max(axis=1))

[6 7 9]


In [ ]:
print(arr.min(axis=0))

[1 1 2]


In [ ]:
print(arr.sum())

38


In [ ]:
print(arr.cumsum(axis=1))

[[ 1  6 12]
 [ 4 11 13]
 [ 3  4 13]]


In [ ]:
a=np.array([[1,2],[3,4]])
b=np.array([[4,3],[2,1]])
print(a+b)

[[5 5]
 [5 5]]


In [ ]:
print(a*b)

[[4 6]
 [6 4]]


In [ ]:
print(a.dot(b))

[[ 8  5]
 [20 13]]


In [ ]:
a=np.array([0,np.pi/2,np.pi])
print(np.sin(a))

[0.0000000e+00 1.0000000e+00 1.2246468e-16]


In [ ]:
a=np.array([0,1,2,3])
print(np.exp(a))

[ 1.          2.71828183  7.3890561  20.08553692]


In [ ]:
print(np.sqrt(a))

[0.         1.         1.41421356 1.73205081]


In [ ]:
arr=np.array([[-1,2,0,4],[4,-0.5,6,0],[2.6,0,7,8],[3,-7,4,2.0]])
inverse=np.linalg.inv(arr)
inverse

array([[ 4.05707196,  1.98511166, -2.28287841,  1.01736973],
       [ 0.50620347,  0.30272953, -0.24813896, -0.01985112],
       [-2.66253102, -1.13151365,  1.50124069, -0.67990074],
       [ 1.01116625,  0.34491315, -0.44665012,  0.26426799]])